Adjust AWS plans' machine types
kyma-project/control-plane pull request #1152
Opened 2021-11-29 08:20 UTC by ksputo

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**
https://github.com/kyma-project/control-plane/issues/1002

2021-11-29 08:24 UTC, k15r commented
Please also update the available machines here: https://github.com/kyma-project/control-plane/blob/main/resources/kcp/charts/kyma-metrics-collector/templates/public-cloud-info-config-map.yaml. Otherwise gathering billing related information will not work for those clusters

2021-11-29 10:01 UTC, ksputo commented
> Please also update the available machines here: https://github.com/kyma-project/control-plane/blob/main/resources/kcp/charts/kyma-metrics-collector/templates/public-cloud-info-config-map.yaml. Otherwise gathering billing related information will not work for those clusters

Done

2021-11-29 10:39 UTC, klaudiagrz submitted a review, later dismissed

2021-11-29 10:45 UTC, klaudiagrz approved these changes

2021-11-29 11:02 UTC, klaudiagrz approved these changes

2021-11-29 11:03 UTC, ksputo commented
/retest

2021-11-29 11:06 UTC, ksputo commented
/hold

2021-11-29 11:07 UTC, PK85 requested changes
schema expose only 6 as u did, but please allow to consume 5 too.

2021-11-30 08:23 UTC, piotrmiskiewicz commented on components/kyma-environment-broker/internal/broker/plans.go
> +	awsHASchema := AWSHASchema([]string{"m6i.2xlarge", "m6i.4xlarge", "m6i.8xlarge", "m6i.12xlarge"})
I think we should allow m5 for awsHA

2021-12-01 08:18 UTC, wozniakjan approved these changes
/lgtm

2021-12-01 08:35 UTC, PK85 approved these changes

2021-12-01 09:06 UTC, piotrmiskiewicz approved these changes

2021-12-01 09:06 UTC, piotrmiskiewicz commented
/retest

2021-12-01 13:30 UTC, klaudiagrz approved these changes

2021-12-01 16:59 UTC, ksputo commented
/unhold

2021-12-02 10:48 UTC, ksputo commented
/test pre-main-control-plane-gke-integration

2021-12-02 11:32 UTC, ksputo commented
/retest

2021-12-02 13:20 UTC, klaudiagrz approved these changes

2021-12-02 18:20 UTC, k15r approved these changes

2021-12-02 18:49 UTC, merged