Replace legacy console URL with Kyma Dashboard
kyma-project/control-plane pull request #1571
Opened 2022-04-13 03:41 UTC by moelsayed

**Description**

Changes proposed in this pull request:

- Replace legacy console URL with Kyma Dashboard
- ...
- ...

**Related issue(s)**

2022-04-20 10:57 UTC, kwiatekus requested changes

2022-04-20 10:57 UTC, kwiatekus commented on components/kyma-environment-broker/internal/broker/instance_create.go
> +	kubeconfigOrigin string
This is representing a kyma dashboard URL ( per landscape ).
Why not calling it this `kymaDashboardBaseURL` instead ? I'm confused with `kubeconfigOrigin`

2022-04-21 13:28 UTC, kwiatekus submitted a review, later dismissed

2022-04-22 14:06 UTC, piotrmiskiewicz commented
please, create a ticket to remove the feature flag when this solution (kyma dashboard) will be enabled in all environmnets. In such ticket we need to remove the feature flag and the old dashboard url logic

2022-04-22 14:09 UTC, piotrmiskiewicz commented
this PR changes dashborad url for new SKRs, but old SKRs will still have the old dashboard url

2022-04-22 14:28 UTC, kwiatekus commented
> this PR changes dashborad url for new SKRs, but old SKRs will still have the old dashboard url, is it ok?

We should also migrate the labels of existing instancses during upgrade

2022-04-26 06:49 UTC, moelsayed commented
@piotrmiskiewicz @kwiatekus Updated to handle existing SKRs, PTAL.

2022-04-26 09:07 UTC, moelsayed commented
/retest

2022-04-26 09:08 UTC, moelsayed commented
/test pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener

2022-04-27 10:22 UTC, szwedm approved these changes
/lgtm

2022-04-27 10:22 UTC, szwedm commented
/retest

2022-04-27 10:57 UTC, merged