Implement dry run mode for upgrade
kyma-project/control-plane pull request #167
Opened 2020-08-28 13:18 UTC by polskikiel

**Description**

Changes proposed in this pull request:

- Implement dry run mode for upgrade

You need to specify the `?dry=true` parameter in the request on `/upgrade/kyma` endpoint in order to run upgrade in dry run mode 

**Related issue(s)**

2020-08-31 11:16 UTC, jasiu001 requested changes

2020-08-31 11:16 UTC, jasiu001 commented on components/kyma-environment-broker/internal/orchestration/kyma/manager.go
> +	case isFinished:
if `dto.Dry` will be true then the strategy will not trigger the `Execute` method with all upgrade processes. How will we see what is the result of all upgrade process?

2020-09-02 05:36 UTC, piotrmiskiewicz commented on components/kyma-environment-broker/internal/orchestration/dto.go
> +	Dry      bool                  `json:"dry,omitempty"`
I would change the name to "DryRun"

2020-09-02 05:37 UTC, piotrmiskiewicz commented on components/kyma-environment-broker/internal/orchestration/handlers/converter_test.go
> +package handlers_test
minor: add "given", "when", "then"

2020-09-02 09:12 UTC, jasiu001 approved these changes

2020-09-02 09:31 UTC, jasiu001 approved these changes

2020-09-02 10:18 UTC, polskikiel commented
/test pre-master-control-plane-gke-integration

2020-09-02 11:45 UTC, merged