Keb gardener machine params
kyma-project/control-plane pull request #175
Opened 2020-09-02 12:30 UTC by piotrmiskiewicz

**Description**

Changes proposed in this pull request:
- make MachineImage and MachineImageVersion gardener params configurable

**Related issue(s)**
RElated: https://github.tools.sap/kyma/backlog/issues/716

2020-09-04 09:50 UTC, ksputo requested changes
please add **APP_PROVISIONING_MACHINE_IMAGE** and **APP_PROVISIONING_MACHINE_IMAGE** to [README.md](https://github.com/kyma-project/control-plane/blob/master/components/kyma-environment-broker/README.md)

2020-09-07 09:16 UTC, klaudiagrz commented on components/kyma-environment-broker/README.md
> +| **APP_PROVISIONING_MACHINE_IMAGE** | Defines the Gardener machine image used in a provisioned node. | None |
```suggestion
| **APP_PROVISIONING_MACHINE_IMAGE** | Defines the Gardener machine image used in a provisioned Node. | None |
```

2020-09-07 09:23 UTC, klaudiagrz approved these changes

2020-09-07 10:52 UTC, ksputo approved these changes

2020-09-07 10:53 UTC, merged