Remove compass-system dependencies
kyma-project/control-plane pull request #2483
Opened 2023-02-15 12:11 UTC by mvshao

**Description**

Changes proposed in this pull request:

- compass-runtime-agent is deployed in the `kyma-system` namespace (previously was `compass-system`)
- removing dependencies to `compass-system` namespace in Provisioner and KEB

**Related issue(s)**
https://github.com/kyma-project/kyma/issues/15915

2023-02-15 12:11 UTC, mvshao commented
/test all

2023-02-15 12:24 UTC, mvshao commented
/retest-required

2023-02-23 09:24 UTC, mvshao commented
/retest

2023-02-23 09:28 UTC, grego952 submitted a review, later dismissed

2023-02-23 09:50 UTC, szwedm submitted a review, later dismissed
/lgtm

2023-02-24 09:46 UTC, koala7659 requested changes
Please remove KymaConfig from this documentatuion. It was for provixioning Kyma versions 
 1.X. We do not support it anymore.

2023-02-24 09:46 UTC, koala7659 commented on docs/provisioner/08-02-provisioning-gardener.md
>              kymaConfig: { # Optional; if you don't provide it, a cluster without Kyma is provisioned
kymaConfig section should not be provided in the case of provisioning version 2.X and higher

2023-02-24 10:03 UTC, koala7659 approved these changes
LGTM

2023-02-24 10:05 UTC, grego952 approved these changes

2023-02-24 10:19 UTC, szwedm approved these changes
/lgtm

2023-02-24 10:28 UTC, merged