bumps containerd to 1.6.18 and goland.org/x/net to 0.8.0 in provisioner
kyma-project/control-plane pull request #2718
Opened 2023-04-28 12:59 UTC by Disper

**Description**

Aims to fix vulnerabilities reported by Whitesource in Provisioner

Changes proposed in this pull request:

- bumps containerd to 1.6.18
- bumps goland.org/x/net to 0.8.0

2023-04-28 13:14 UTC, mvshao commented on resources/kcp/values.yaml
> +          version: "PR-2718"
Is the indentation needed?

2023-04-28 13:22 UTC, mvshao requested changes

2023-04-28 13:22 UTC, mvshao commented on resources/kcp/values.yaml
> +          version: "PR-2718"
`PR-2718` doesn't exist in `europe-docker.pkg.dev/kyma-project/prod/control-plane`, see line 7. This image is in `/dev/control-plane/`

2023-05-02 06:25 UTC, rakesh-garimella commented
/test pre-main-control-plane-reconciler-e2e-latest-release

2023-05-02 10:43 UTC, Disper commented
Added `/do-not-merge/hold` until the additional review will be done. @kyma-project/gopher could you see if you're fine with [the small structure change](https://github.com/kyma-project/control-plane/pull/2718/files#diff-61f7248e5a92221c2cd603ec6a9714363cfc901c42d661a71522c8910e6d3fef)?

2023-05-02 11:23 UTC, rakesh-garimella commented
/test pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener

2023-05-04 13:32 UTC, Disper commented
I've received a hint from @szwedm that it might not work as we're trying to change override for this
https://github.com/kyma-project/control-plane/blob/main/resources/kcp/values.yaml#L7

See this:
https://github.com/kyma-project/control-plane/blob/main/resources/kcp/charts/provisioner/templates/deployment.yaml#L45

2023-05-08 11:10 UTC, koala7659 requested changes
Please see my comment and update image tag

2023-05-08 11:10 UTC, koala7659 commented on resources/kcp/charts/provisioner/values.yaml
> +      version: "PR-17433"
Most likely copy-paste bug. Please change it to PR-2718

2023-05-08 11:17 UTC, koala7659 approved these changes
LGTM

2023-05-08 11:18 UTC, mvshao approved these changes
LGTM

2023-05-08 11:36 UTC, merged