Adapt provisioner for running local
kyma-project/control-plane pull request #2918
Opened 2023-07-13 11:19 UTC by VOID404

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2023-07-13 11:19 UTC, VOID404 commented
This PR will require some changes in management plane config
/hold

2023-07-13 11:44 UTC, VOID404 commented
/retest

2023-07-13 15:22 UTC, VOID404 commented
/retest

2023-07-14 07:38 UTC, VOID404 commented
/retest

2023-07-14 10:53 UTC, Disper requested changes
Please remember about updating https://github.com/kyma-project/control-plane/blob/main/components/provisioner/README.md

2023-07-14 10:56 UTC, mvshao requested changes
Please bump the Provisioner images

2023-07-14 13:10 UTC, VOID404 commented
/retest

2023-07-17 07:43 UTC, VOID404 commented
/retest

2023-07-17 11:12 UTC, mvshao reviewed
Thanks for bumping the image!

2023-07-18 07:23 UTC, Disper approved these changes
I see that this PR was attached to another one when I left some comments https://github.com/kyma-project/control-plane/pull/2886#pullrequestreview-1534314621. The comments there related to those parts are not a request for changes so I'm giving an LGTM here to make it easier to work on the other PR.

2023-07-18 11:11 UTC, grego952 commented on components/provisioner/README.md
> +Afterwards the database has to be created and migrations have to be run.
```suggestion
Afterwards, the database must be created, and migrations must be run.
```

2023-07-18 11:11 UTC, grego952 commented on components/provisioner/README.md
> +| APP_GARDENER_AUDIT_LOGS_POLICY_CONFIG_MAP                     | Name of the Config Map containing the audit logs policy                                                   | optional
```suggestion
| APP_GARDENER_AUDIT_LOGS_POLICY_CONFIG_MAP                     | Name of the ConfigMap containing the audit logs policy                                                   | optional                                                                |
```

2023-07-18 11:15 UTC, VOID404 commented on components/provisioner/README.md
> +Runtime Provisioner also needs a kubeconfig for a garden and auth data for Director.
Both should be understandable. 
Gardener garden, where seeds are planted and shoots grow ;)

2023-07-19 08:17 UTC, mvshao approved these changes

2023-07-25 07:43 UTC, VOID404 commented
/retest

2023-07-25 11:04 UTC, mvshao approved these changes

2023-07-25 11:25 UTC, grego952 approved these changes

2023-07-26 07:10 UTC, VOID404 commented
/retest

2023-07-26 08:26 UTC, i332322 commented
/test pre-main-kcp-cli

2023-07-26 11:00 UTC, VOID404 commented
/retest

2023-07-27 07:20 UTC, VOID404 commented
/test tide

2023-07-27 07:34 UTC, merged