Bump Go in provisioner
kyma-project/control-plane pull request #3113
Opened 2023-10-11 16:59 UTC by VOID404

**Description**

Changes proposed in this pull request:

**Related issue(s)**

2023-10-12 06:46 UTC, VOID404 commented
/retest

2023-10-16 07:40 UTC, koala7659 requested changes
Please check my comment

2023-10-16 07:40 UTC, koala7659 commented on resources/kcp/charts/provisioner/values.yaml
> +      version: "PR-3113"
we cannot update the image version here to the one taken from dev repo

2023-10-16 13:41 UTC, VOID404 commented
/retest

2023-10-16 14:11 UTC, VOID404 commented
/test all

2023-10-17 07:15 UTC, koala7659 approved these changes
LGTM

2023-10-18 05:18 UTC, gczuczy approved these changes

2023-10-18 05:34 UTC, merged