Remove obsolete L2/L3 operator bindings from provisioner
kyma-project/control-plane pull request #3438
Opened 2024-05-17 06:30 UTC by ebensom

**Description**

Changes proposed in this pull request:

The L2 and L3 operator bindings were for a legacy (OIDC based) approach to authorize SAP operator access to SKRs, but are not needed any more. 

**Related issue(s)**

https://github.tools.sap/kyma/backlog/issues/5553

2024-05-20 14:03 UTC, koala7659 requested changes
Please see my comments.

2024-05-21 07:00 UTC, ebensom commented on components/provisioner/internal/operations/stages/provisioning/create_operators_bindings.go
>  	groupKindSubject = "Group"
Done.

2024-05-21 07:01 UTC, ebensom commented on components/provisioner/internal/operations/stages/provisioning/create_operators_bindings_test.go
> +		for i, administrator := range cluster.Administrators {
Done, added a second administrator for the test.

2024-05-21 07:09 UTC, koala7659 approved these changes
LGTM

2024-05-21 07:10 UTC, merged