Update based on latest logging chart changes
kyma-project/control-plane pull request #446
Opened 2021-01-15 13:20 UTC by rakesh-garimella

**Description**

Changes proposed in this pull request:

- Update the override keys based on the chart refactoring

**Related issue(s)**

2021-01-18 13:58 UTC, rakesh-garimella commented
/test pre-control-plane-components-kyma-environment-broker

2021-01-18 14:55 UTC, suleymanakbas91 requested changes

2021-01-18 14:55 UTC, suleymanakbas91 commented on components/kyma-environment-broker/internal/process/provisioning/audit_log_step.go
>  		{Key: "fluent-bit.conf.extra", Value: fmt.Sprintf(`
```suggestion
		{Key: "fluent-bit.config.extra", Value: fmt.Sprintf(`
```

2021-01-27 14:20 UTC, rakesh-garimella commented
/retest

2021-02-03 12:59 UTC, rakesh-garimella commented
/test pre-master-control-plane-integration

2021-02-03 13:23 UTC, suleymanakbas91 approved these changes

2021-02-05 12:02 UTC, ebensom approved these changes

2021-02-23 12:40 UTC, piotrmiskiewicz approved these changes

2021-02-23 13:04 UTC, merged