complete refactoring
kyma-project/control-plane pull request #63
Opened 2020-07-20 02:44 UTC by maksd

Changes proposed in this pull request:

- adding new metrics
- adding caching
- adding grafana dashboard
- adding new unit tests

2020-07-20 02:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-project/control-plane?pullRequest=63) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-project/control-plane?pullRequest=63) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-project/control-plane?pullRequest=63) it.</sub>

2020-07-20 19:52 UTC, maksd commented
/test pre-master-control-plane-integration

2020-08-02 01:51 UTC, maksd commented
/test pre-master-control-plane-gke-integration

2020-08-03 13:25 UTC, maksd commented
/test pre-master-control-plane-gke-integration

2020-09-07 07:51 UTC, ebensom submitted a review, later dismissed

2020-09-07 08:11 UTC, alexandra-simeonova requested changes
Technical writer review

2020-09-07 08:11 UTC, alexandra-simeonova commented on components/metris/README.md
> +| `--log-level` | **METRIS_LOGLEVEL** | Logging level. (debug,info,warn,error) | `info` |
Keeping the entries consistent with earlier ones, including formatting and periods at the end of phrases.
```suggestion
| `--edp-buffer` | **EDP_BUFFER** | Number of events that the buffer can have | `100` |
| `--edp-workers` | **EDP_WORKERS** | Number of workers to send metrics | `5` |
| `--edp-event-retry` | **EDP_RETRY** | Number of retries for sending an event | `5` |
| `--provider-poll-interval` | **PROVIDER_POLLINTERVAL** | Interval at which metrics are fetched | `1m` |
| `--provider-workers` | **PROVIDER_WORKERS** | Number of workers to fetch metrics | `10` |
| `--provider-buffer` | **PROVIDER_BUFFER** | Number of clusters that the buffer can have | `100` |
| `--listen-addr` | **METRIS_LISTEN_ADDRESS** | Address and port the metrics and health HTTP endpoints will bind to | None |
| `--debug-port` | **METRIS_DEBUG_PORT** | Port the debug HTTP endpoint will bind to (always listen on localhost) | None |
| `--config-file` | None | Location of the `config` file | None |
| `--kubeconfig` | **METRIS_KUBECONFIG** | Path to the Gardener `kubeconfig` file | None |
| `--log-level` | **METRIS_LOGLEVEL** | Logging level (`debug`,`info`,`warn`,`error`) | `info` |
```

2020-09-08 07:07 UTC, alexandra-simeonova approved these changes

2020-09-08 12:22 UTC, maksd commented
/test pre-master-control-plane-integration

2020-09-14 13:15 UTC, merged